const knowledgeData = [
    // ── Menstrual Health ──
    { topic: 'period_pain', category: 'menstrual_health', title: 'Managing Period Pain (Dysmenorrhea)', content: 'Period pain is caused by uterine contractions. Home remedies include applying a warm water bottle to the lower abdomen, gentle exercises like walking or yoga, staying hydrated, and avoiding caffeine. Over-the-counter pain relievers like ibuprofen can help. If pain is severe, interferes with daily life, or is accompanied by heavy bleeding, consult a gynecologist.', tags: ['period', 'pain', 'cramps', 'dysmenorrhea'], source: 'WHO Women\'s Health Guidelines' },
    { topic: 'menstrual_cycle', category: 'menstrual_health', title: 'Understanding Your Menstrual Cycle', content: 'A normal menstrual cycle lasts 21-35 days. The cycle has four phases: menstruation (3-7 days), follicular phase, ovulation, and luteal phase. Track your cycle to understand your body. Irregular periods can be caused by stress, weight changes, PCOS, or thyroid issues. If your cycle is consistently irregular, consult a doctor.', tags: ['cycle', 'tracking', 'irregular', 'phases'], source: 'ACOG' },
    { topic: 'menstrual_hygiene', category: 'menstrual_health', title: 'Menstrual Hygiene Practices', content: 'Change pads/tampons every 4-6 hours. Wash hands before and after changing. Use clean, dry undergarments. Avoid scented products near genitals. Menstrual cups are a safe, eco-friendly alternative. Dispose of sanitary products properly wrapped in paper.', tags: ['hygiene', 'pad', 'tampon', 'cup', 'sanitation'], source: 'UNICEF' },
    { topic: 'pcos', category: 'menstrual_health', title: 'PCOS Awareness', content: 'Polycystic Ovary Syndrome affects 1 in 10 women. Symptoms include irregular periods, acne, weight gain, excessive hair growth, and difficulty conceiving. PCOS is manageable with lifestyle changes (exercise, balanced diet), medication, and medical supervision. Early diagnosis helps prevent complications. If you suspect PCOS, consult a gynecologist.', tags: ['pcos', 'ovary', 'hormonal', 'irregular'], source: 'WHO' },
    { topic: 'when_to_see_doctor_periods', category: 'menstrual_health', title: 'When to See a Doctor About Periods', content: 'See a doctor if: periods are absent for 3+ months, bleeding lasts more than 7 days, you soak through a pad/tampon every hour, you experience severe pain not relieved by over-the-counter medication, there is unusual discharge or odor, or you bleed between periods.', tags: ['doctor', 'warning', 'heavy', 'absent'], source: 'NHS' },

    // ── Pregnancy ──
    { topic: 'early_pregnancy_signs', category: 'pregnancy', title: 'Early Signs of Pregnancy', content: 'Common early signs include missed period, nausea/morning sickness, breast tenderness, fatigue, frequent urination, and mood changes. A home pregnancy test is most accurate after a missed period. If the test is positive, schedule an appointment with a gynecologist for confirmation and prenatal care.', tags: ['pregnancy', 'signs', 'symptoms', 'test'], source: 'Mayo Clinic' },
    { topic: 'prenatal_care', category: 'pregnancy', title: 'Prenatal Care Essentials', content: 'Start prenatal vitamins (folic acid) early. Schedule regular check-ups. Eat a balanced diet rich in iron, calcium, and protein. Stay hydrated. Avoid alcohol, smoking, and raw/undercooked foods. Get adequate rest. Exercise moderately unless advised otherwise. Take prescribed supplements.', tags: ['prenatal', 'care', 'vitamins', 'checkup'], source: 'WHO' },
    { topic: 'pregnancy_warning_signs', category: 'pregnancy', title: 'Warning Signs During Pregnancy', content: 'Seek immediate medical help if you experience: heavy vaginal bleeding, severe headache with blurred vision, high fever, severe abdominal pain, sudden swelling of face or hands, reduced baby movement, or water breaking before 37 weeks. These could indicate serious complications.', tags: ['warning', 'emergency', 'complications', 'bleeding'], source: 'ACOG' },
    { topic: 'nutrition_pregnancy', category: 'pregnancy', title: 'Nutrition During Pregnancy', content: 'Eat plenty of fruits, vegetables, whole grains, lean protein, and dairy. Key nutrients: folic acid (prevents neural tube defects), iron (prevents anemia), calcium (builds baby\'s bones), DHA (brain development). Avoid raw fish, unpasteurized dairy, excessive caffeine, and alcohol.', tags: ['nutrition', 'diet', 'food', 'vitamins'], source: 'WHO' },
    { topic: 'postpartum_care', category: 'pregnancy', title: 'Postpartum Care and Recovery', content: 'Recovery takes 6-8 weeks. Rest when baby sleeps. Eat nutritious meals. Stay hydrated. Watch for signs of postpartum depression: persistent sadness, loss of interest, difficulty bonding with baby, extreme fatigue, anxiety. Attend postnatal check-ups. It is okay to ask for help.', tags: ['postpartum', 'recovery', 'depression', 'newborn'], source: 'NHS' },

    // ── Sexual Consent ──
    { topic: 'understanding_consent', category: 'sexual_consent', title: 'Understanding Sexual Consent', content: 'Consent is a clear, voluntary, enthusiastic agreement to engage in a specific activity. Consent must be: freely given (no coercion), reversible (can be withdrawn at any time), informed (both parties understand what they agree to), enthusiastic (not just absence of no), and specific (consent to one act does not mean consent to all acts).', tags: ['consent', 'agreement', 'voluntary', 'rights'], source: 'UN Women' },
    { topic: 'boundaries', category: 'sexual_consent', title: 'Setting Personal Boundaries', content: 'You have the right to set boundaries in any relationship. Communicate your limits clearly. No means no — no explanation is needed. Boundaries can change, and that is okay. A partner who respects you will respect your boundaries. If someone violates your boundaries, it is not your fault.', tags: ['boundaries', 'rights', 'respect', 'limits'], source: 'RAINN' },
    { topic: 'what_is_harassment', category: 'sexual_consent', title: 'What Counts as Sexual Harassment', content: 'Sexual harassment includes: unwanted touching, sexual comments or jokes, stalking, sending unsolicited sexual content, groping, catcalling, workplace sexual advances, and any unwelcome sexual behavior. In India, sexual harassment is punishable under IPC Section 354 (using criminal force against a woman) and Section 509 (insulting modesty). The Vishakha Guidelines protect against workplace harassment.', tags: ['harassment', 'law', 'workplace', 'vishakha'], source: 'IPC & Supreme Court of India' },
    { topic: 'reporting_harassment', category: 'sexual_consent', title: 'How to Report Sexual Harassment', content: 'Steps to report: 1) Document everything (dates, times, details, witnesses). 2) Report to the Internal Complaints Committee (ICC) at workplace, or the Local Complaints Committee. 3) File an FIR at the nearest police station. 4) Call Women Helpline 181. 5) Contact the National Commission for Women. You can also file an online complaint at ncw.nic.in.', tags: ['report', 'complaint', 'fir', 'police'], source: 'NCW India' },

    // ── Contraception ──
    { topic: 'contraception_methods', category: 'contraception', title: 'Contraception Methods Overview', content: 'Available methods: 1) Barrier methods (male/female condoms, diaphragm). 2) Hormonal methods (oral pills, patches, injections, implants). 3) Intrauterine devices (copper IUD, hormonal IUD). 4) Natural methods (fertility awareness, withdrawal — less reliable). 5) Permanent methods (tubectomy, vasectomy). Effectiveness varies. Consult a doctor to find the best method for you.', tags: ['contraception', 'birth control', 'methods', 'pills'], source: 'WHO' },
    { topic: 'emergency_contraception', category: 'contraception', title: 'Emergency Contraception', content: 'Emergency contraceptive pills (like i-pill or Unwanted-72) can prevent pregnancy if taken within 72 hours of unprotected intercourse. They are more effective the sooner they are taken. They are available over the counter at pharmacies. They are NOT regular contraception and should not be used frequently. Consult a doctor after use.', tags: ['emergency', 'pill', 'ipill', 'morning after'], source: 'FOGSI India' },
    { topic: 'contraception_myths', category: 'contraception', title: 'Common Contraception Myths', content: 'Myth: Contraception causes infertility — Fact: Most methods are reversible. Myth: Only women need to worry about contraception — Fact: It is a shared responsibility. Myth: Natural methods are always safe — Fact: They have higher failure rates. Myth: You cannot get pregnant while breastfeeding — Fact: Breastfeeding is not a reliable contraceptive.', tags: ['myths', 'facts', 'misconceptions'], source: 'WHO' },

    // ── Mental Wellbeing ──
    { topic: 'stress_management', category: 'mental_wellbeing', title: 'Stress Management Techniques', content: 'Effective techniques: deep breathing exercises (4-7-8 technique), progressive muscle relaxation, regular physical exercise, adequate sleep (7-9 hours), limiting caffeine, talking to trusted people, journaling, mindfulness meditation, taking breaks from screens. If stress persists for weeks, consider professional counselling.', tags: ['stress', 'relaxation', 'breathing', 'exercise'], source: 'WHO Mental Health' },
    { topic: 'anxiety_coping', category: 'mental_wellbeing', title: 'Coping with Anxiety', content: 'Grounding techniques: 5-4-3-2-1 method (5 things you see, 4 you touch, 3 you hear, 2 you smell, 1 you taste). Practice deep breathing. Challenge anxious thoughts with evidence. Maintain a routine. Limit news and social media if triggering. Exercise regularly. Seek professional help if anxiety interferes with daily life. In India, call iCall: 9152987821.', tags: ['anxiety', 'grounding', 'panic', 'worry'], source: 'NIMHANS' },
    { topic: 'depression_signs', category: 'mental_wellbeing', title: 'Recognizing Signs of Depression', content: 'Signs include: persistent sadness lasting 2+ weeks, loss of interest in activities, changes in appetite or weight, sleeping too much or too little, fatigue, difficulty concentrating, feelings of worthlessness, and thoughts of self-harm. Depression is treatable with therapy, medication, or both. Reach out to a mental health professional. In India, call Vandrevala Foundation: 1860-2662-345.', tags: ['depression', 'sadness', 'signs', 'treatment'], source: 'NIMHANS' },
    { topic: 'self_care', category: 'mental_wellbeing', title: 'Self-Care Practices', content: 'Daily self-care: maintain sleep schedule, eat nutritious meals, stay hydrated, move your body, connect with people who support you, set boundaries, limit screen time before bed, spend time in nature, practice gratitude, do something you enjoy every day. Self-care is not selfish — it is necessary.', tags: ['self-care', 'wellbeing', 'routine', 'daily'], source: 'WHO' },
    { topic: 'crisis_resources', category: 'mental_wellbeing', title: 'Mental Health Crisis Resources in India', content: 'If you or someone you know is in crisis: iCall: 9152987821 (8 AM-10 PM). Vandrevala Foundation: 1860-2662-345 (24/7). Snehi: 044-24640050 (2 PM-10 PM). AASRA: 9820466726 (24/7). Remember: seeking help is a sign of strength, not weakness. You are not alone.', tags: ['crisis', 'helpline', 'suicide', 'emergency'], source: 'NIMHANS' },
];

module.exports = knowledgeData;
